import LocalizedStrings from 'react-localization';

export enum Languages {
  RU = 'ru-RU',
  EN = 'en-EN',
}

export const Strings = new LocalizedStrings({
  [Languages.RU]: {
    header: 'Руководитель проекта',
    description: 'Создайте новый этап или просмотри существующий',
    createMilestone: 'Создать этап',
    create: 'Создать',
    editMilestone: 'Редактировать этап',
    edit: 'Редактировать',
    showMore: 'Показать ещё',
    titleLabel: 'Заголовок',
    descriptionLabel: 'Описание',
    startLabel: 'Начало',
    endLabel: 'Окончание',
    save: 'Сохранить',
    cancel: 'Отмена',
    search: 'Поиск',
    open: 'Открытые',
    test: 'Тестирование',
    complete: 'Выполненные',
    empty: 'Нет записей',
    issues: 'Задачи',
    days: 'Дней',
    light: 'Светлая',
    dark: 'Тёмная',
  },
  [Languages.EN]: {
    header: 'Project Manager',
    description: 'Project of a new stage or review',
    createMilestone: 'Create milestone',
    create: 'Create',
    editMilestone: 'Edit milestone',
    edit: 'Edit',
    showMore: 'Show more',
    titleLabel: 'Title',
    descriptionLabel: 'Description',
    startLabel: 'Start',
    endLabel: 'End',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    open: 'Open',
    test: 'Tests',
    complete: 'Complete',
    empty: 'Empty',
    issues: 'Issues',
    days: 'Days',
    light: 'Light',
    dark: 'Dark',
  },
});
